<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <AvaloniaVersion>11.1.0</AvaloniaVersion>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    
<!--    // tên phiên bản //-->
    <Product>CTU-Scheduler</Product>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <InformationalVersion>1.0.0</InformationalVersion>
  </PropertyGroup>
</Project>
